Feature/nickname
mash-up-kr/DamgleDamgle_Android pull request #15
Opened 2022-07-25 16:09 UTC by Sookhee

- 닉네임 생성 화면 추가
- Retrofit + Moshi 네트워크 모듈 추가
- https://api-dev.damgle.com/v1/namepicker API를 통해 랜덤 닉네임 생성

2022-07-25 16:10 UTC, Sookhee commented
네트워크 모듈 추가했는데 PR이 너무 커지는거같아서 우선 header에 토큰 넣는거나 BaseRequest, BaseResponse 이런건 필요할 때 추가로 작성하도록 해도 괜찮을까요?

2022-07-27 16:03 UTC, Sookhee commented on data/src/main/java/com/mashup/damgledamgle/repository/spec/NickNameRequest.kt
> +data class NickNameRequest(
아 이거 Response로 바꿔야 한다...;;

2022-07-27 17:47 UTC, dahyun1226 requested changes
1. 아이디 랜덤으로 바뀌면서 같은거 걸리면 다시 돌려주던가 해야할듯? 돌리는 의미가 없으니까.
아니면 api 자체를 좀 바꿔달라고 요청하던지!

2. 이름 변하면 밑줄도 사이즈 변하는게 기획적으로 맞는건지? (약간 어색함이 있네요)

3. 네트워크 끄면 앱 터집니닷. 
android.util.MalformedJsonException 뜨는거 같아요 (맞는지 모름). 수정부탁드립니다!

2022-07-27 17:47 UTC, dahyun1226 commented on app/src/main/java/com/mashup/damgledamgle/presentation/feature/onboarding/NickNameScreen.kt
>  @Composable
요거 따로 패키지 빼줘도 될듯? 하네요
큰 상관은 없습니당

2022-07-27 17:47 UTC, dahyun1226 commented on app/src/main/java/com/mashup/damgledamgle/presentation/feature/onboarding/NickNameScreen.kt
> +                                )
refresh 함수 두 개로 분리하는게 더 깔끔할거같아요
(내부적으로 refreshNickName쓰더라두?)

2022-07-27 17:47 UTC, dahyun1226 commented on app/src/main/java/com/mashup/damgledamgle/presentation/feature/onboarding/NickNameScreen.kt
> +    NickNameBox("닉네임")
리프레시가 약간 아래인듯하네요

2022-07-27 17:47 UTC, dahyun1226 commented on data/src/main/java/com/mashup/damgledamgle/repository/remote/OnboardingRepositoryImpl.kt
> +        }
```suggestion
                val resultData = when {
            adjective != null -> ServiceBuilder.damgleApi.getNickName(adjective = adjective)
            noun != null -> ServiceBuilder.damgleApi.getNickName(noun = noun)
            else -> ServiceBuilder.damgleApi.getNickName()
        }
```
개인적으로 패턴매칭을 굉장히 좋아합니다! 더 깔끔하게 느껴져요

2022-07-29 16:10 UTC, Sookhee commented
리뷰 반영했습니다

그리고...

1. 아이디 랜덤으로 바뀌면서 같은거 걸리면 다시 돌려주던가 해야할듯? 돌리는 의미가 없으니까.
아니면 api 자체를 좀 바꿔달라고 요청하던지!
====> 나중에 서버쪽에 물어보고 변경해달라고 합시다! ㅎㅎ. 그리고 지금 중복 아이디도 내려오고 있는거같은데 이 부분도 말해봐야할거같아여

2. 이름 변하면 밑줄도 사이즈 변하는게 기획적으로 맞는건지? (약간 어색함이 있네요)
====> 내일 QA하면서 물어보고 UI 수정하겠습니당

네트워크 끄면 앱 터집니닷.
android.util.MalformedJsonException 뜨는거 같아요 (맞는지 모름). 수정부탁드립니다!
====> 네트워크 통신 보내는 부분부터 try/catch로 잡아서 처리했습니다. 나중에 NetworkResponse.Error면 다이얼로그 띄우는거 추가할게여

2022-07-30 06:06 UTC, merged